//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomCar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int IDItem { get; set; }
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Service { get; set; }
    
        public virtual Service Service1 { get; set; }
    }
}
