//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomCar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int IDRoute { get; set; }
        public string Time { get; set; }
        public string CoordinatesALength { get; set; }
        public string CoordinatesAWidth { get; set; }
        public string CoordinatesBLength { get; set; }
        public string CoordinatesBWidth { get; set; }
        public Nullable<int> TravelLength { get; set; }
        public Nullable<int> AverageSpeed { get; set; }
        public Nullable<int> FuelConsumption { get; set; }
        public Nullable<int> TravelInfoID { get; set; }
    
        public virtual TravelInfo TravelInfo { get; set; }
    }
}
