//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomCar
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TravelInfo()
        {
            this.Route = new HashSet<Route>();
        }
    
        public int IDTravelInfo { get; set; }
        public string Status { get; set; }
        public Nullable<int> DriverID { get; set; }
        public Nullable<double> TravelLength { get; set; }
        public Nullable<int> DaysExpected { get; set; }
        public Nullable<int> StartCity { get; set; }
        public Nullable<int> StopCity { get; set; }
        public Nullable<int> CarID { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        public virtual Driver Driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Route> Route { get; set; }
    }
}
